# Generated by Django 4.1.7 on 2023-04-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='username',
            new_name='name',
        ),
    ]
