# Generated by Django 4.2 on 2023-05-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_alter_label_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='executor',
        ),
    ]
